# Generated by Django 5.1.7 on 2025-04-15 19:18

from django.db import migrations
from django.db import models


def invert_existing_offset_values(apps, schema_editor):
    WorkflowTrigger = apps.get_model("documents", "WorkflowTrigger")
    WorkflowTrigger.objects.filter(
        type=4,
    ).update(schedule_offset_days=models.F("schedule_offset_days") * -1)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1065_workflowaction_assign_custom_fields_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtrigger",
            name="schedule_offset_days",
            field=models.IntegerField(
                default=0,
                help_text="The number of days to offset the schedule trigger by.",
                verbose_name="schedule offset days",
            ),
        ),
        migrations.RunPython(
            code=invert_existing_offset_values,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
